name: tests
run-name: ${{ github.actor }} ran the all tests.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install
      - name: check TypeScript
        run: yarn run tsc:check
      - name: check Eslint;
        run: yarn run eslint:check
      - name: run unit tests
        run: yarn run test
